apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-latency
spec:
  groups:
    - name: latency.rules
      rules:
        - alert: HighLatency
          expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: High request latency