name: 🚀 Deploy Lab 5 - Instrumentation Lab

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: '18.x'
  environment: dev
  region: westus
  resourceGroup: NickClarkRG
  webAppName: webapp-dev

jobs:
  deploy:
    name: 💡 Deploy Infra and Node.js App
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔐 Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚀 Deploy Bicep Template
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: resourcegroup
          resourceGroupName: NickClarkRG
          template: AZ-400/labs/lab-5-az400-instrumentation-lab/infra/main.bicep
          parameters: AZ-400/labs/lab-5-az400-instrumentation-lab/infra/parameters.dev.json
          deploymentName: lab5-${{ github.run_number }}
          deploymentMode: Incremental

      - name: 🚀 Zip and Deploy Node.js App
        run: |
          cd AZ-400/labs/lab-5-az400-instrumentation-lab/app
          zip -r app.zip .
          az webapp deploy \
            --resource-group ${{ env.resourceGroup }} \
            --name ${{ env.webAppName }} \
            --src-path app.zip \
            --type zip